name: Continuous Integration Pipeline

on: [push]

jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules # Caching ~/.npm to accelerate CI
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - uses: actions/setup-node@v3
        with:
          node-version: "16.18"

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Documentation-check
        run: yarn check:eslint-docs
      - name: Lint
        run: yarn lint
      - name: Type-check
        run: yarn typecheck
      - name: Run Unit tests
        run: yarn test

  PublishToNpm:
    needs: RunTests
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - run: yarn
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
